from enum import Enum


class IncidentType(str, Enum):
    INFRASTRUCTURE = "INFRASTRUCTURE"
    APPLICATION = "APPLICATION"
    NETWORK = "NETWORK"
    DATABASE = "DATABASE"
    SECURITY = "SECURITY"
    KUBERNETES = "KUBERNETES"
    PERFORMANCE = "PERFORMANCE"
    THIRD_PARTY = "THIRD_PARTY"
    DEPLOYMENT = "DEPLOYMENT"
    UNKNOWN = "UNKNOWN"
